"""Modify full_name to first, middle, and last name

Revision ID: b62d08152c82
Revises: 16cc5c3f198b
Create Date: 2025-07-17 03:06:27.508395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62d08152c82'
down_revision: Union[str, Sequence[str], None] = '16cc5c3f198b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('firstname', sa.String(length=100), nullable=False))
    op.add_column('student', sa.Column('middlename', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('lastname', sa.String(length=100), nullable=False))
    op.alter_column('student', 'previous_school',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('student', 'photo_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('student_admission_number_key'), 'student', type_='unique')
    op.drop_column('student', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('student_admission_number_key'), 'student', ['admission_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('student', 'photo_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('student', 'previous_school',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('student', 'lastname')
    op.drop_column('student', 'middlename')
    op.drop_column('student', 'firstname')
    # ### end Alembic commands ###
